CasusBelli/CasusBelli.UI/Areas/Admin/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CasusBelli.Domain.Abstract;
using CasusBelli.Domain.Entities;

namespace CasusBelli.UI.Areas.Admin.Controllers
{
    public class ImageController : Controller
    {
        //
        // GET: /Admin/Image/

        private ITypeRepository typeRepository;
        private ISubTypeRepository subTypeRepository;
        public ImageController(ITypeRepository repository, ISubTypeRepository subType)
        {
            typeRepository = repository;
            subTypeRepository = subType;
        }

        public FileContentResult GetImageSubType(int SubTypeId)
        {
            ProductSubType prod = subTypeRepository.ProductSubTypes.FirstOrDefault(p => p.SubTypeId == SubTypeId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeData);
            }
            else
            {
                return null;
            }
        }

        public FileContentResult GetImageType(int TypeId)
        {
            ProductType prod = typeRepository.Types.FirstOrDefault(p => p.TypeId == TypeId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeData);
            }
            else
            {
                return null;
            }
        }

    }
}

CasusBelli/CasusBelli.UI/Areas/Admin/Controllers/TypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CasusBelli.Domain.Abstract;
using CasusBelli.Domain.Entities;

namespace CasusBelli.UI.Areas.Admin.Controllers
{
    [Authorize]
    public class TypesController : Controller
    {
        //
        // GET: /Admin/Types/
        private ITypeRepository typeRepository;

        public TypesController(ITypeRepository typeRep)
        {
            typeRepository = typeRep;
        }

        #region TypesActions
        public ViewResult Index()
        {
            return View(typeRepository.Types);
        }

        public ViewResult EditType(int id)
        {
            ProductType prod = typeRepository.Types.FirstOrDefault(p => p.TypeId == id);
            if (prod != null)
                return View(prod);
            else
            {
                throw new HttpException(404, "Such type doesnt exist");
            }
        }

        [HttpPost]
        public ActionResult EditType(ProductType productType, HttpPostedFileBase image)
        {
            if (ModelState.IsValid && productType.TypeId > 0)
            {
                //if (image != null)
                //{
                //    productType.ImageMimeData = image.ContentType;
                //    byte[] bt = new byte[image.ContentLength];
                //    image.InputStream.Read(bt, 0, image.ContentLength);
                //    productType.ImageData = bt;//NullableHelper.ConvertArray(bt);
                //}
                //else
                //{
                //    ProductType oldtype = typeRepository.Types.FirstOrDefault(p => p.TypeId == productType.TypeId);
                //    productType.ImageData = oldtype.ImageData;
                //}
                typeRepository.AddOrUpdateType(productType);
                TempData["message"] = string.Format("Зміни типу до {0} було збережено", productType.TypeName);
                return RedirectToAction("Index");
            }
            else
            {
                return View(productType);
            }
        }

        public ActionResult DeleteType(int id)
        {
            ProductType type = typeRepository.Types.FirstOrDefault(p => p.TypeId == id);
            typeRepository.DeleteType(type);
            TempData["message"] = string.Format("Тип {0} було видалено", type.TypeId);
            return RedirectToAction("Index");
        }

        public ActionResult CreateType()
        {
            return View(new ProductType());
        }

        [HttpPost]
        public ActionResult CreateType(ProductType productType, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                //if (image != null)
                //{
                //    productType.ImageMimeData = image.ContentType;
                //    byte[] bt = new byte[image.ContentLength];
                //    image.InputStream.Read(bt, 0, image.ContentLength);
                //    productType.ImageData = bt; //NullableHelper.ConvertArray(bt);
                //}
                productType.TypeId = typeRepository.Types.Max(p => p.TypeId) + 1;
                typeRepository.AddOrUpdateType(productType);
                return RedirectToAction("Index");
            }
            else
            {
                return View(productType);
            }
        }
        #endregion

    }
}

CasusBelli/CasusBelli.UI/Areas/Admin/Views/Types/CreateType.cshtml
@model CasusBelli.Domain.Entities.ProductType

@{
    ViewBag.Title = "CreateType";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}

<h2>CreateType</h2>

@using (Html.BeginForm("CreateType", "Types", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ProductType</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.TypeName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TypeName)
            @Html.ValidationMessageFor(model => model.TypeName)
        </div>
        
        <div class="editor-label"><label for="Photo">Image</label></div>
        <div class="ProductType">
            @*@if (Model.ImageData == null)
            {
                @:None
        }
            else
            {
                <img width="150" height="150" src="@Url.Action("GetImageType", "Image", new { Model.TypeId })" />
            }
            <div>Upload new image: <input type="file" name="Image" /></div>*@
            <img width="150" height="150" src="@Model.Photo" />
            <div class="editor-field">
                @Html.EditorFor(model => model.Photo)
                @Html.ValidationMessageFor(model => model.Photo)
            </div>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TypeText)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TypeText)
            @Html.ValidationMessageFor(model => model.TypeText)
        </div>

        @*<div class="editor-label">
        @Html.LabelFor(model => model.Photo)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Photo)
        @Html.ValidationMessageFor(model => model.Photo)
    </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.AdditionalInfo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdditionalInfo)
            @Html.ValidationMessageFor(model => model.AdditionalInfo)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Types")
</div>

CasusBelli/CasusBelli.UI/Areas/Admin/Views/Types/EditType.cshtml
@using System.Xml
@model CasusBelli.Domain.Entities.ProductType

@{
    ViewBag.Title = "EditType";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}

<h1>@Model.TypeName</h1>

@using (Html.BeginForm("EditType", "Types", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.EditorForModel()
    <div class="editor-label"><label for="CountryName">Image</label></div>
    <div class="ProductType">
        @*@if (Model.ImageData == null)
        {
            @:None
        }
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImageType", "Image", new { Model.TypeId })"/>
        }
        <div>Upload new image: <input type="file" name="Image"/></div>*@
        

        @*<img width="150" height="150" src="@Model.Photo" />
        <div class="editor-field">
            @Html.EditorFor(model => model.Photo)
            @Html.ValidationMessageFor(model => model.Photo)
        </div>*@
    </div>
    <input type="submit" value="Зберегти зміни"/><br />
    @Html.ActionLink("Відмінити зміни", "Index")<br /><br />
}

CasusBelli/CasusBelli.UI/Areas/Admin/Views/Types/Index.cshtml
@model IEnumerable<CasusBelli.Domain.Entities.ProductType>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}

<fieldset>
    <h2>Types</h2>

    <p>
        @Html.ActionLink("Create New", "CreateType")
    </p>
    <table border="1">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeText)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdditionalInfo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypeText)
                </td>
                <td>
                    <div class="ProductType">
                        @*@if (item.ImageData == null)
                        {
                            @:None
                                                            }
                        else
                        {
                            <img width="150" height="150" src="@Url.Action("GetImageType", "Image", new { item.TypeId })" />
                        }*@
                        <img width="150" height="150" src="@item.Photo" />
                    </div>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdditionalInfo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditType", new { id = item.TypeId }) |
                    @Html.ActionLink("Delete", "DeleteType", new { id = item.TypeId })
                </td>
            </tr>
        }


    </table>
</fieldset>