CasusBelli/CasusBelli.UI/Models/SubTypesViewModel.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CasusBelli.Domain.Abstract;
using CasusBelli.Domain.Entities;
using Microsoft.Ajax.Utilities;

namespace CasusBelli.UI.Models
{
    public class SubTypesViewModel:ProductSubType
    {

        private ITypeRepository type;
        private ICountryRepository country;
        private IProductRepository product;

        private List<Product> ProductsOfST;
        [HiddenInput(DisplayValue = false)]
        public List<ProductType> AvailableTypes { get; set; }
        [HiddenInput(DisplayValue = false)]
        public List<Country> AvailableCountries { get; set; }
        [HiddenInput(DisplayValue = false)]
        public String TypeName { get; set; }
        public String CountryName { get; set; }

        public bool IsOutOfRange { get; set; }
        public SubTypesViewModel()
        {
            
        }
        public SubTypesViewModel(ITypeRepository typeRep, ICountryRepository countryRep, IProductRepository productRep)
        {
            type = typeRep;
            AvailableTypes = typeRep.Types.ToList();
            country = countryRep;
            AvailableCountries = country.Countries.ToList();
            product = productRep;
            ProductsOfST = product.Products.Where(p=>p.SubTypeId == SubTypeId).ToList();
        }
        public SubTypesViewModel(ProductSubType productSubTypes, List<ProductType> availableTypes, List<Country> availableCountries, List<Product> myProducts)
        {
            AdditionalInfo = productSubTypes.AdditionalInfo;
            AvailableTypes = availableTypes;
            AvailableCountries = availableCountries;
            Photo = productSubTypes.Photo;
            Price = productSubTypes.Price;
            SubTypeId = productSubTypes.SubTypeId;
            SubTypeName = productSubTypes.SubTypeName;
            SubTypeText = productSubTypes.SubTypeText;
            TypeId = productSubTypes.TypeId;
            CountryId = productSubTypes.CountryId;
            TypeName = availableTypes.First(p => p.TypeId == productSubTypes.TypeId).TypeName;
            CountryName = availableCountries.First(p => p.CountryId == productSubTypes.CountryId).CountryName;
            ImageData = productSubTypes.ImageData;
            ImageMimeData = productSubTypes.ImageMimeData;

            IsOutOfRange = !(myProducts.Count > 0);
        }

        public SubTypesViewModel(ProductSubType productSubTypes, List<Country> availableCountries)
        {
            AdditionalInfo = productSubTypes.AdditionalInfo;
            AvailableTypes = new List<ProductType>();
            AvailableCountries = availableCountries;
            Photo = productSubTypes.Photo;
            Price = productSubTypes.Price;
            SubTypeId = productSubTypes.SubTypeId;
            SubTypeName = productSubTypes.SubTypeName;
            SubTypeText = productSubTypes.SubTypeText;
            TypeId = productSubTypes.TypeId;
            CountryId = productSubTypes.CountryId;
            TypeName = "";
            CountryName = availableCountries.First(p => p.CountryId == productSubTypes.CountryId).CountryName;
            ImageData = productSubTypes.ImageData;
            ImageMimeData = productSubTypes.ImageMimeData;
        }
    }
}

CasusBelli/CasusBelli.UI/Areas/Admin/Controllers/SubTypesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CasusBelli.Domain.Abstract;
using CasusBelli.Domain.Concrete;
using CasusBelli.Domain.Entities;
using CasusBelli.UI.Models;

namespace CasusBelli.UI.Areas.Admin.Controllers
{
    public class SubTypesController : Controller
    {
        //
        // GET: /Admin/SubTypes/

        private ISubTypeRepository subTypeRepository;
        private ITypeRepository typeRepository;
        private ICountryRepository countryRepository;
        private IProductRepository productRepository;

        public SubTypesController(ISubTypeRepository subTypeRep, ITypeRepository typeRep, ICountryRepository countryRep, IProductRepository prodRep)
        {
            subTypeRepository = subTypeRep;
            typeRepository = typeRep;
            countryRepository = countryRep;
            productRepository = prodRep;
        }

        public ViewResult Index()
        {
            List<SubTypesViewModel> subtypes = new List<SubTypesViewModel>();
            var s = subTypeRepository.ProductSubTypes.ToList();
            foreach (ProductSubType ps in s)
            {
                var watch = Stopwatch.StartNew();
                // the code that you want to measure comes here (Time measuring)

                List<Country> countries = countryRepository.Countries.ToList();
                watch.Stop();
                var elapsedMs = watch.ElapsedMilliseconds;

                subtypes.Add(new SubTypesViewModel(ps, countries));
            }
            return View(subtypes);
        }

        public ViewResult EditSubType(int id)
        {
            SubTypesViewModel model;
            try
            {
                 model =
                    new SubTypesViewModel(subTypeRepository.ProductSubTypes.First(p => p.SubTypeId == id),
                        typeRepository.Types.ToList(), countryRepository.Countries.ToList(),
                        productRepository.Products.Where(p => p.SubTypeId == id).ToList());
            }
            catch(Exception ex)
            {
                throw new HttpException(404, "Such subtype doesnt exist");
            }
            return View(model);

        }

        [HttpPost]
        public ActionResult EditSubType(SubTypesViewModel subTypesViewModel, HttpPostedFileBase image)
        {
            try
            {
                if (ModelState.IsValid &&
                    subTypeRepository.ProductSubTypes.First(p => p.SubTypeId == subTypesViewModel.SubTypeId) != null)
                {
                    if (image != null)
                    {
                        subTypesViewModel.ImageMimeData = image.ContentType;
                        byte[] bt = new byte[image.ContentLength];
                        image.InputStream.Read(bt, 0, image.ContentLength);
                        subTypesViewModel.ImageData = bt; //NullableHelper.ConvertArray(bt);
                    }
                    subTypeRepository.AddOrUpdateSubType(subTypesViewModel);
                    TempData["message"] = string.Format("Зміни підтипу до {0} було збережено",
                        subTypesViewModel.SubTypeName);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(subTypesViewModel);
                }
            }
            catch (Exception ex)
            {
                throw new HttpException(404, "Such subtype doesnt exist");
            }
        }

        public ActionResult DeleteSubType(int id)
        {
            ProductSubType subtype = subTypeRepository.ProductSubTypes.FirstOrDefault(p => p.SubTypeId == id);
            subTypeRepository.DeleteSubType(subtype);
            TempData["message"] = string.Format("Підтип {0} було видалено", subtype.TypeId);
            return RedirectToAction("Index");
        }

        public ActionResult CreateSubType()
        {
            return View(new SubTypesViewModel(new EFProductTypeRepository(), new EFCountryRepository(), new EFProductRepository()));
        }

        [HttpPost]
        public ActionResult CreateSubType(SubTypesViewModel productSubType, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    productSubType.ImageMimeData = image.ContentType;
                    byte[] bt = new byte[image.ContentLength];
                    image.InputStream.Read(bt, 0, image.ContentLength);
                    productSubType.ImageData = bt;//NullableHelper.ConvertArray(bt);
                }
                productSubType.SubTypeId = subTypeRepository.ProductSubTypes.Max(p => p.SubTypeId) + 1;
                subTypeRepository.AddOrUpdateSubType(productSubType);
                return RedirectToAction("Index");
            }
            else
            {
                productSubType.AvailableTypes = typeRepository.Types.ToList();
                return View(productSubType);
            }
        }
    }
}

CasusBelli/CasusBelli.UI/Areas/Admin/Views/SubTypes/CreateSubType.cshtml
@model CasusBelli.UI.Models.SubTypesViewModel

@{
    ViewBag.Title = "CreateSubType";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}

<h2>CreateSubType</h2>

@using (Html.BeginForm("CreateSubType", "SubTypes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SubTypesViewModel</legend>

        <div class="editor-label"><label for="TypeName">TypeName</label></div>
        <div class="editor-field">
            @Html.DropDownListFor(modelItem => Model.TypeId, new SelectList(Model.AvailableTypes, "TypeId", "TypeName"))
        </div>
        
        <div class="editor-label"><label for="CountryName">CountryName</label></div>
        <div class="editor-field">
            @Html.DropDownListFor(modelItem => Model.CountryId, new SelectList(Model.AvailableCountries, "CountryId", "CountryName"))
        </div>
        
        <div class="editor-label"><label for="Image">Image</label></div>
        <div class="ProductType">
            @*@if (Model.ImageData == null)
            {
                @:None
        }
            else
            {
                <img width="150" height="150" src="@Url.Action("GetImageSubType", "Home", new {Model.SubTypeId})" />
            }
            <div>Upload new image: <input type="file" name="Image" /></div>*@
        </div>

        <div class="editor-field">
            @Html.EditorFor(model => model.TypeId)
            @Html.ValidationMessageFor(model => model.TypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubTypeName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SubTypeName)
            @Html.ValidationMessageFor(model => model.SubTypeName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubTypeText)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SubTypeText)
            @Html.ValidationMessageFor(model => model.SubTypeText)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Photo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Photo)
            @Html.ValidationMessageFor(model => model.Photo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AdditionalInfo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdditionalInfo)
            @Html.ValidationMessageFor(model => model.AdditionalInfo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "SubTypes")
</div>

CasusBelli/CasusBelli.UI/Areas/Admin/Views/SubTypes/EditSubType.cshtml
@model CasusBelli.UI.Models.SubTypesViewModel

@{
    ViewBag.Title = "EditSubType";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}

<h2>EditSubType</h2>

<h1>@Model.SubTypeName</h1>

@using (Html.BeginForm("EditSubType", "SubTypes", FormMethod.Post, new {enctype = "multipart/form-data"}))
{

    <div class="editor-label"><label for="TypeName">TypeName</label></div>
    <div class="editor-field">
        @Html.DropDownListFor(modelItem => Model.TypeId, new SelectList(Model.AvailableTypes, "TypeId", "TypeName"))
    </div>
    
    <div class="editor-label"><label for="CountryName">CountryName</label></div>
    <div class="editor-field">
        @Html.DropDownListFor(modelItem => Model.CountryId, new SelectList(Model.AvailableCountries, "CountryId", "CountryName"))
    </div>
    
    <div class="editor-label"><label for="CountryName">Image</label></div>
    <div class="ProductType">
        @*@if (Model.ImageData == null)
        {
            @:None
        }
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImageSubType", "Image", new {Model.SubTypeId})"/>
        }
        <div>Upload new image: <input type="file" name="Image"/></div>*@
    </div>
    
    @Html.EditorForModel()
    <input type="submit" value="Зберегти зміни" />
    @Html.ActionLink("Відмінити зміни", "Index")
}

CasusBelli/CasusBelli.UI/Areas/Admin/Views/SubTypes/Index.cshtml
@model List<CasusBelli.UI.Models.SubTypesViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}

<fieldset>
    <h2>SubTypes</h2>

    <p>
        @Html.ActionLink("Create New", "CreateSubType")
    </p>
    <table border="1">
        <tr>
            <th>
                SubTypeName
            </th>
            <th>
                SubTypeText
            </th>
            <th>
                Photo
            </th>
            <th>
                AdditionalInfo
            </th>
            <th>
                Country
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SubTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubTypeText)
                </td>
                <td>
                    <div class="ProductType">
                        @*@if (item.ImageData == null)
                        {
                            @:None
                                    }
                        else
                        {
                            <img width="150" height="150" src="@Url.Action("GetImageSubType", "Image", new {item.SubTypeId})" />
                        }*@
                        <img width="150" height="150" src="@item.Photo" />
                    </div>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdditionalInfo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CountryName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditSubType", new { id = item.SubTypeId }) |
                    @Html.ActionLink("Delete", "DeleteSubType", new { id = item.SubTypeId })
                </td>

            </tr>
        }


    </table>
</fieldset>